"""Framework-independent formation geometry."""

from uav_swarm_control.formations.metrics import (
    RigidAlignment,
    formation_diameter,
    normalized_shape_mse,
    normalized_shape_rmse,
    pairwise_distances,
    position_mse,
    position_rmse,
    position_sse,
    rigid_alignment,
    shape_mse,
    shape_rmse,
    shape_sse,
    squared_position_errors,
    squared_shape_errors,
)
from uav_swarm_control.formations.templates import (
    FormationKind,
    create_formation,
    cubic_lattice,
    line,
    regular_polygon,
    spherical_shell,
    square,
    square_grid,
    square_pyramid,
    triangle,
)
from uav_swarm_control.formations.transforms import (
    center,
    rotate,
    rotation_matrix_from_euler,
    scale,
    transform,
    translate,
    validate_rotation_matrix,
)

__all__ = [
    "FormationKind",
    "RigidAlignment",
    "center",
    "create_formation",
    "cubic_lattice",
    "formation_diameter",
    "line",
    "normalized_shape_mse",
    "normalized_shape_rmse",
    "pairwise_distances",
    "position_mse",
    "position_rmse",
    "position_sse",
    "regular_polygon",
    "rigid_alignment",
    "rotate",
    "rotation_matrix_from_euler",
    "scale",
    "shape_mse",
    "shape_rmse",
    "shape_sse",
    "spherical_shell",
    "square",
    "square_grid",
    "square_pyramid",
    "squared_position_errors",
    "squared_shape_errors",
    "transform",
    "translate",
    "triangle",
    "validate_rotation_matrix",
]
